### ISSUE TITLE
doc.cls

### ISSUE THREAD

**Issue by kohlhase** [angerhang/mockDoc#2]
you should have `doc.cls` so that you can also run it through `pdflatex`

**Comment by jinbozz** [comment]
Done.

**Comment by jinbozz** [comment]
Currently I need to load article.cls for some macros, I will try not to load it tomorrow.

**Comment by kohlhase** [comment]
Indeed,  you should not load article.cls (and I think you do not need it).

**Comment by jinbozz** [comment]
2+ hours work. Actually it is much more time-consuming than I expected. The main problem is that I don't know what is defined in article.cls and what is defined in LaTeX2e source file. I checked article.cls. Doesn't help me a lot. Failing to define \Large leads to "undefined control sequence" error, which costs me more than 1hr to realize it is caused by \Large.

Is there any recommended reading about writing classes in lower-latex language? I found two readings, which are

http://www.tug.org/texlive/Contents/live/texmf-dist/doc/latex/base/source2e.pdf 
http://www.latex-project.org/guides/clsguide.pdf

The first one is about source code, over 400 pages, seems need months to read through.
I carefully read the second one, still, it can't solve my problem.

By the way, I also tried to use \@startsection to rewrite doc.cls. But I am not so clear about \@startsection, and I can't add the counter, any advice?

Jinbo

ps: go swimming now~

**Comment by dginev** [comment]
Your biggest problem will indeed be with finding well written TeX documentation. TeX packages tend to leave their very intricate internals largely/completely undocumented. To counter that, you should develop the skill of reading through the LaTeXML bindings and tracing commands of interest. As a rule of thumb LaTeXML bindings are much easier to read than TeX package files.

Also, if an error message confuses you - make it a habit of asking other LaTeXML devs what the mistake might be. We can also improve cryptic messages, when you hit badly implemented reporting.

**Comment by kohlhase** [comment]
yes, reading LaTeX packages and classes is an art that you have to learn over time, but it will come; keep at it. LaTeX error messages are also cryptic, but again, you will learn. If these things were easy, I would have no incentive to pay you :-).

stackoverflow is a great help to me in writing LaTeX, but I guess reading these kind of files is different. 

Michael

**Comment by kohlhase** [comment]
oh, and if you are stuck you can come by and maybe I can see what is going on.

**Comment by kohlhase** [comment]
I guess you can close this issue.
